openapi: 3.0.3
info:
  title: BetterReads Platform API
  description: |-
    BetterReads OpenAPI Spec Document for implementing and interacting with the BetterReads API.
  contact:
    email: robertjhird@gmail.com
  version: 0.0.1
externalDocs:
  description: BetterReads Repository
  url: https://github.com/CelestialDragonFly/BetterReads-Platform
servers:
  - url: https://todo.when.hosting
tags:
  - name: books
    description: APIs for retrieving information about books

paths:
  /books:
    get:
      tags:
        - books
      summary: Query books from the book API
      description: Retrieve a list of books by the requested query parameter.
      parameters:
        - in: query
          name: request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBooksRequest"
      responses:
        "200":
          description: A list of books
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBooksResponse"
        "400":
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    GetBooksRequest:
      type: object
      properties:
        query:
          type: string
          description: A general search mechanism, intended to be used by a search bar with user input.
          example: the lord of the rings
        title:
          type: string
          description: Query books by their title.
          example: harry potter
        author:
          type: string
          description: Query books by their author.
          example: jk rowling
        subject:
          type: string
          description: Query books about subjects.
          example: software engineering
        place:
          type: string
          description: Query books about locations.
          example: lisbon
        language:
          type: string
          description: Query books written in the requested language.
          enum:
            - eng
            - rus
            - swe
            - fre
            - kor
            - ger
            - tur
            - jpn
            - cat
            - glg
            - por
            - pol
            - slo
            - cze
            - bul
            - dut
            - ita
            - spa
          example: eng
        publisher:
          type: string
          description: Query books by publisher.
          example: penguin random house

    GetBooksResponse:
      type: object
      required:
        - books
      properties:
        books:
          type: array
          items:
            $ref: "#/components/schemas/Book"

    Book:
      type: object
      required:
        - id
        - title
        - author
        - genre
        - book_image
        - description
        - language

      properties:
        id:
          type: string
          description: Unique identifier for the book
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        book_image:
          type: string
        published_date:
          type: string
          format: date
        description:
          type: string
        language:
          type: string
          enum:
            - eng
            - rus
            - swe
            - fre
            - kor
            - ger
            - tur
            - jpn
            - cat
            - glg
            - por
            - pol
            - slo
            - cze
            - bul
            - dut
            - ita
            - spa

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: INVALID_PARAMETER
        message:
          type: string
          description: Error message
          example: Invalid language parameter value
        details:
          type: object
          description: Additional error details
