openapi: 3.0.3
info:
  title: BetterReads Platform API
  description: |-
    BetterReads OpenAPI Spec Document for implementing and interacting with the BetterReads API.
  contact:
    email: robertjhird@gmail.com
  version: 0.0.3
externalDocs:
  description: BetterReads Repository
  url: https://github.com/CelestialDragonFly/BetterReads-Platform
servers:
  - url: https://todo.when.hosting/
tags:
  - name: books
    description: APIs for retrieving information about books

paths:
  /api/v1/books:
    get:
      tags:
        - books
      summary: Query books from the book API
      description: Retrieve a list of books by the requested query parameters.
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: A general search mechanism, intended to be used by a search bar with user input.
          example: the lord of the rings
        - in: query
          name: title
          schema:
            type: string
          description: Query books by their title.
          example: harry potter
        - in: query
          name: author
          schema:
            type: string
          description: Query books by their author.
          example: jk rowling
        - in: query
          name: subject
          schema:
            type: string
          description: Query books about subjects.
          example: software engineering
        - in: query
          name: place
          schema:
            type: string
          description: Query books about locations.
          example: lisbon
        - in: query
          name: publisher
          schema:
            type: string
          description: Query books by publisher.
          example: penguin random house
      responses:
        "200":
          description: A list of books
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBooksResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    GetBooksResponse:
      type: object
      required:
        - books
      properties:
        books:
          type: array
          items:
            $ref: "#/components/schemas/Book"

    Book:
      type: object
      required:
        - id
        - title
        - author_name
        - author_id
        - book_image
        - published_year
        - isbn
        - rating_count
        - rating_average
        - source

      properties:
        id:
          type: string
          description: Unique identifier for the book
        title:
          type: string
        author_name:
          type: string
        author_id:
          type: string
        book_image:
          type: string
        published_year:
          type: integer
        isbn:
          type: string
        rating_count:
          type: integer
        rating_average:
          type: number
        source:
          type: string

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: INVALID_PARAMETER
        message:
          type: string
          description: Error message
          example: Invalid language parameter value
        details:
          type: object
          description: Additional error details
